# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minibridge < Formula
  desc "Minibridge securely connects Agents to MCP servers, exposing them to the internet while enabling optional integration with remote or local Policers for authentication, analysis, and transformation."
  homepage "https://github.com/acuvity/minibridge"
  version "0.7.0"
  license "Apache"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/acuvity/minibridge/releases/download/v0.7.0/minibridge_0.7.0_darwin_amd64.zip"
      sha256 "53c8f63fa20c8ec5d5b3a4a1f2fe8f5dde160ee33f9ca861df0715c7eb630941"

      def install
        bin.install "minibridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/acuvity/minibridge/releases/download/v0.7.0/minibridge_0.7.0_darwin_arm64.zip"
      sha256 "d40e432107d7183d44b86e29b218a1375181887f2440813c7426690fe7d39f8d"

      def install
        bin.install "minibridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/acuvity/minibridge/releases/download/v0.7.0/minibridge_0.7.0_linux_amd64.zip"
      sha256 "97b1d94ddaa816d57da9528b632a74753a71e9cc5e0c79bda48d2a332e38aa45"
      def install
        bin.install "minibridge"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/acuvity/minibridge/releases/download/v0.7.0/minibridge_0.7.0_linux_arm64.zip"
      sha256 "435c111d4b9f619d8dbf6467d2a364110a3ee9dc06e599ee9012ce536b166d63"
      def install
        bin.install "minibridge"
      end
    end
  end

  test do
    system "#{bin}/minibridge", "--version"
  end
end
