# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minibridge < Formula
  desc "Minibridge securely connects Agents to MCP servers, exposing them to the internet while enabling optional integration with remote or local Policers for authentication, analysis, and transformation."
  homepage "https://github.com/acuvity/minibridge"
  version "0.6.1"
  license "Apache"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/acuvity/minibridge/releases/download/v0.6.1/minibridge_0.6.1_darwin_amd64"
      sha256 "92f36946bfa41cf431d71fded5defffe0266e1258adec936d0012f65b0327eac"

      def install
        bin.install "minibridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/acuvity/minibridge/releases/download/v0.6.1/minibridge_0.6.1_darwin_arm64"
      sha256 "6644d34c22adfb34882ab6f9a42c617d2fe5e5aa3df7a0a1f7538ec789a37d20"

      def install
        bin.install "minibridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acuvity/minibridge/releases/download/v0.6.1/minibridge_0.6.1_linux_amd64"
        sha256 "1a87db379c533d95480ca26d57988ec21d2899070dbe64c9d774347d0c056647"

        def install
          bin.install "minibridge"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acuvity/minibridge/releases/download/v0.6.1/minibridge_0.6.1_linux_arm64"
        sha256 "366c13a319c6b0f2168fc71a23819ab3228d42f8f992a6e7e0e8c516736e1e82"

        def install
          bin.install "minibridge"
        end
      end
    end
  end

  test do
    system "#{bin}/minibridge", "--version"
  end
end
