# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minibridge < Formula
  desc "Minibridge securely connects Agents to MCP servers, exposing them to the internet while enabling optional integration with remote or local Policers for authentication, analysis, and transformation."
  homepage "https://github.com/acuvity/minibridge"
  version "0.6.2"
  license "Apache"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/acuvity/minibridge/releases/download/v0.6.2/minibridge_0.6.2_darwin_amd64.zip"
      sha256 "41d45a1d08a31733dbeffab7f1813c963e3950bc881527796e0d9aa22c48251d"

      def install
        bin.install "minibridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/acuvity/minibridge/releases/download/v0.6.2/minibridge_0.6.2_darwin_arm64.zip"
      sha256 "d9e24eaba98517f7cebf15e7289c6e371109b9b4c7adaf6092f9adc89f0b8c0b"

      def install
        bin.install "minibridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acuvity/minibridge/releases/download/v0.6.2/minibridge_0.6.2_linux_amd64.zip"
        sha256 "30de5073f9fc95b2bc3a6462a8a29e0c84af5ad8fdbf27c8b99f8c0bd4c91310"

        def install
          bin.install "minibridge"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acuvity/minibridge/releases/download/v0.6.2/minibridge_0.6.2_linux_arm64.zip"
        sha256 "0ee5c5cc6d01f8112e30dbc23967f38f5a13503368c3b30b7eb6922a43c0b68b"

        def install
          bin.install "minibridge"
        end
      end
    end
  end

  test do
    system "#{bin}/minibridge", "--version"
  end
end
